'''
# This file is part of pyemaps
# ___________________________
#
# pyemaps is free software for non-comercial use: you can 
# redistribute it and/or modify it under the terms of the GNU General 
# Public License as published by the Free Software Foundation, either 
# version 3 of the License, or (at your option) any later version.
#
# pyemaps is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with pyemaps.  If not, see <https://www.gnu.org/licenses/>.
#
# Contact supprort@emlabsoftware.com for any questions and comments.
# ___________________________
'''

from copy import copy

rel_stage = 'Stable'
pyemaps_samples_dir = 'pyemaps_samples'

def copy_samples():
    '''
    Copies sample code from package directory to current diretory 
    for easy access
    '''
    import os, sys
    import shutil

    curr_dir = os.getcwd()
    
    q = str(f"Copy pyemaps samples into {pyemaps_samples_dir} in current directory?\n ")
    
    inp = input(q +"[Y/n] ")

    if inp and not inp.lower().strip()[:1] == "y":
        print("No sample code is copied!")
        sys.exit(1)

    curr_samples_dir = os.path.join(curr_dir, pyemaps_samples_dir)

    if not os.path.exists(curr_samples_dir):
        os.makedirs(curr_samples_dir)
    
    pyemaps_pkgdir = os.path.dirname(os.path.abspath(__file__))
    pkg_samples_dir = os.path.join(pyemaps_pkgdir, "samples")

    for file_name in os.listdir(pkg_samples_dir):
        
        if file_name == 'si_pyemaps.py':
            continue
        source = os.path.join(pkg_samples_dir, file_name)
        destination = os.path.join(curr_samples_dir, file_name)
        
        if os.path.isfile(source):
            shutil.copy(source, destination)
            print(f'Copied sample code: {file_name} in pyemaps package to {destination}')

    print(f'Run sample code by typing: \"python pyemaps_samples\<sample>\"')

def main():
    """
    Liveness test and other information of pemaps run on command line. 
    The purpose of the run run is to show diffraction patterns 
    generated by pyemaps for silicon crystal.

    Usage:
        python -m pyemaps -s (--sample)
        python -m pyemaps -c (--copyright)
        python -m pyemaps -cp (--copysamples)
        python -m pyemaps -v (--version)
        python -m pyemaps -l (--license) <empty|license token>

    """
    
    try:
        from .samples.si_pyemaps import run_si_sample
        
        from emaps import PKG_TYPE, TYPE_FREE, TYPE_FULL, TYPE_UIUC
        if PKG_TYPE != TYPE_FREE:
            from emaps import stem4d 
        
    except ImportError as e:
        print(f"Error importing built-in sample: {e}")
        
    import argparse
    import datetime
    import pkg_resources

    parser = argparse.ArgumentParser(description="pyemaps console script options parsing")
    
    parser.add_argument("-c", 
                        "--copyright", 
                        default=False, 
                        action='store_true',
                        help="display pyEMAPS copyrights", 
                        required=False)
    parser.add_argument("-cp", 
                        "--copysamples", 
                        default=False, 
                        action='store_true',
                        help="copy sample code into working directory", 
                        required=False)
    
    if PKG_TYPE != TYPE_FREE:
        parser.add_argument("-l", 
                            "--license", 
                            nargs='?', 
                            const='',   
                            default=None,   
                            metavar='LICENSE_TOKEN',
                            help="activate license for full package with 4D STEM features. Leave LICENSE_TOKEN empty for 7 days trial license", 
                            required=False
                            )
    parser.add_argument("-s", 
                        "--sample",
                        default=False, 
                        action='store_true',
                        help="run basic pyEMAPS sample code", 
                        required=False)
    parser.add_argument("-v", 
                        "--version", 
                        default=False, 
                        help="display pyEMAPS version", 
                        action='store_true',
                        required=False)
   
    try:
        args = parser.parse_args()
    except argparse.ArgumentTypeError as e:
        print(f"Argument validation error: {e}")
        parser.print_help()
        exit(1)
    except SystemExit as e:
        print(f"Parsing failed with exit code {e}. Invalid input or argument format.")
        parser.print_help()
        exit(1)

    ver = pkg_resources.require("pyemaps")[0].version + str(f" {rel_stage}").lower()
    
    copyrit = ['PyEMAPS - Transmission Electron Diffraction Simulations In Python']
    copy1 = '© 2021-' + datetime.date.today().strftime('%Y') + ' EMLab Solutions, Inc. All rights reserved.'
    
    vers = 'Free version ' + ver
    if PKG_TYPE == TYPE_UIUC:
        vers = "Full version " + ver +" for use exclusively at University of Illinois at Urbana Champaign." 
    
    if PKG_TYPE == TYPE_FULL:
        vers = "Full version " + ver +" with 4DSTEM features." 

    copyrit.append(copy1)
    scopyrit = '\n'.join(copyrit)

    if args.version:
        print(f'pyEMAPS {vers.lower()}')
        exit(0)
    elif args.copyright: 
        print(scopyrit)
        exit(0)  
    else:
        copyrit.append(vers)
        copyrit.append('--------------------------------')
        print('\n'.join(copyrit)) 
          
        if args.copysamples:
            copy_samples()
            exit(0)
        
        if args.sample:
            run_si_sample()
            exit(0)
        
        if args.license is not None:

            if PKG_TYPE == TYPE_FREE:
                print(f'License is required only for a full pyemaps package with 4DSTEM features')
                print(f'Contact support@emlabsoftware.com for how to download and install the full package')
                exit(0)

            lic_token = args.license
            if lic_token is None or lic_token == '':
                ret = stem4d.activate_license_once()
            else:
                ret = stem4d.activate_license_bytoken_once(lic_token)
            if ret == 0:
                exit(0)

            exit(1)
    

if __name__ == '__main__':
    main()  