
import os
from pathlib import Path
from pyemaps import StackImage, EM_INT

current_file = Path(os.path.abspath(__file__))
samples_path = current_file.parent.absolute()

def getADFFn():
    '''
    Imports sample experimental diffraction pattern image
    with preprietory 8-bytes header. 
    '''
    return os.path.join(samples_path, 'adftest30x30.im3')

def test_adf():
    '''
    Searches and indexes imported diffraction pattern images
    by theoretical diffraction patterns generated by pyemaps.
    '''
    
    adfn = getADFFn()
    img = StackImage(adfn,ndtype = EM_INT)
    # adfimgfn = getADFFn()
    img.generateADF(center = (256.0, 256.0), 
                    rads = (50.0,200.0), 
                    scol = 30,
                    bShow = True)

    # # release ediom module memory.
    # release_ediom()

if __name__ == '__main__':
    
    test_adf()
    